services:
  - type: web
    name: erc-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FINANCE_TEMP_PASSWORD
        sync: false
      - key: FINANCE_ALLOWED_USERS
        sync: false
      - key: NODE_ENV
        value: production
